initial_behavior: idle
switchable_components: [CImp, JntLimit, PoseIntRight, PoseIntLeft, JntImp, TrajectoryGeneratorJoint, RightForceControl, LeftForceControl, RightForceTransformation, LeftForceTransformation, lli_hi_tx]
behaviors: 
  - name: idle
    running: [lli_hi_tx]
  - name: CartImp
    running: [CImp, JntLimit, PoseIntLeft, PoseIntRight, lli_hi_tx]
  - name: JntImp
    running: [JntImp, TrajectoryGeneratorJoint, lli_hi_tx]
  - name: CartFCL
    running: [CImp, PoseIntRight, PoseIntLeft, RightForceControl, LeftForceControl, RightForceTransformation, LeftForceTransformation, lli_hi_tx]


